version: '3'
services:
  # web_prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prod
  #   ports:
  #       - "80:5000"
  web_debug:
    build:
        context: .
        dockerfile: Dockerfile.debug
    ports:
      - "5000:5000"